tasks:
  - name: Journal
    command: |
      cat >>/home/gitpod/.bashrc <<EOF
      export GEM_HOME=/workspace/.rvm
      export GEM_PATH=\$GEM_HOME:\$GEM_PATH
      EOF
      source /home/gitpod/.bashrc

      ./journal install
      ./journal start

ports:
  - port: 4000
    onOpen: open-browser
    visibility: private

vscode:
    extensions:
        - bierner.markdown-preview-github-styles
        - DavidAnson.vscode-markdownlint
        - eamodio.gitlens
        - EditorConfig.EditorConfig
        - jock.svg
        - sissel.shopify-liquid
        - timonwong.shellcheck
        - usernamehw.errorlens
