# Site settings
title: Daniel's Journal
author: Daniel Dietrich
email: cafebab3@gmail.com
description: >-
  Data for my future avatar.
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://danieldietrich.dev"
github_repo: "https://github.com/danieldietrich/journal"

# Google Analytics (gtag)
google_analytics: G-377JP30S7M

# Social links
twitter_username: danieldietrich
github_username: danieldietrich
linkedin_username: daniel-dietrich-kiel

# Permalinks
permalink: /:title/

# Set to true to show excerpts on the homepage
show_excerpts: true

# Reading time configuration
reading_time:
  words_per_minute: 180 # Average words per minute reading, default to 180

# Markdown parser & converter
kramdown:
  footnote_backlink: "\u21B5"

# Header pages in order as they should show up
header_pages:
  - about.md

# Minify output
sass:
  style: compressed

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - journal
  - LICENSE.txt
  - README.md
